name: "버그 신고"
description: "버그를 신고합니다."
title: "[Bug] "
labels: ["bug"]
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 결과
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 참고 자료

  - type: checkboxes
    id: checklist
    attributes:
      label: 체크리스트
      options:
        - label: 같은 버그가 이미 등록되어 있는지 확인했습니다.
          required: true
        - label: 비밀번호, API 키 등 민감한 정보를 제거했습니다.
          required: true
