name: "버그 신고"
description: "버그를 신고합니다."
title: "[Bug] "
labels: ["bug"]
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 재현 방법
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 기대 결과
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 참고 자료
