name: "문서 작업 요청"
description: "문서의 추가, 수정 또는 개선을 요청하거나 제안합니다."
title: "[Documentation] "
labels: ["documentation"]
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: 문서 작업 설명
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 작업 이유
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 참고 사항
