name: "기능 요청"
description: "새로운 기능의 추가 또는 기존 기능의 개선을 요청하거나 제안합니다."
title: "[Feature] "
labels: ["enhancement"]
type: feature
body:
  - type: textarea
    id: description
    attributes:
      label: 기능 설명
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 요청 이유
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 참고 사항
